dbpass = "88LcNrALs5NpRjjF"
dbhost = "leoselfcloud.top"
dbport = "3306"
dbname = "hire"
dbuser = "hire"

# dbpass = "Kidduomude1412*"
# dbhost = "localhost"
# dbport = "3306"
# dbname = "COMP639"
# dbuser = "root"