# dbpass = "88LcNrALs5NpRjjF"
# dbhost = "leoselfcloud.top"
# dbport = "3306"
# dbname = "hire"
# dbuser = "hire"

dbpass = "Kidduomude1412"
dbhost = "127.0.0.1"
dbport = "3306"
dbname = "hire_local"
dbuser = "root"